"""
reporting/navigator_export.py — MITRE ATT&CK Navigator layer export.

Generates a Navigator 4.x layer JSON file from Sentinel_Fusion pipeline
alerts. The layer can be imported directly into:
    https://mitre-attack.github.io/attack-navigator/

Each detected technique is highlighted with a confidence-based colour and
score. Duplicate techniques are merged — the highest-confidence instance wins.

Stateless. No external dependencies.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone


# ---------------------------------------------------------------------------
# MITRE tactic ID → Navigator tactic slug
# ---------------------------------------------------------------------------

_TACTIC_SLUG: dict[str, str] = {
    "TA0001": "initial-access",
    "TA0002": "execution",
    "TA0003": "persistence",
    "TA0004": "privilege-escalation",
    "TA0005": "defense-evasion",
    "TA0006": "credential-access",
    "TA0007": "discovery",
    "TA0008": "lateral-movement",
    "TA0009": "collection",
    "TA0010": "exfiltration",
    "TA0011": "command-and-control",
    "TA0040": "impact",
    "TA0042": "resource-development",
    "TA0043": "reconnaissance",
}

# Regex: T followed by 4 digits, optional .NNN sub-technique suffix
_TECHNIQUE_RE = re.compile(r"(T\d{4}(?:\.\d{3})?)")
# Regex: TA followed by 4 digits
_TACTIC_ID_RE = re.compile(r"(TA\d{4})")


def _parse_technique_id(raw: str) -> str | None:
    """Extract 'T1234' or 'T1234.001' from a mitre_technique string."""
    if not raw:
        return None
    m = _TECHNIQUE_RE.search(raw)
    return m.group(1) if m else None


def _parse_tactic_slug(raw: str) -> str | None:
    """Extract the Navigator tactic slug from a mitre_tactic string."""
    if not raw:
        return None
    m = _TACTIC_ID_RE.search(raw)
    if not m:
        return None
    return _TACTIC_SLUG.get(m.group(1))


def _confidence_to_color(confidence: float) -> str:
    """Map alert confidence (0–1) to a Navigator hex colour."""
    if confidence >= 0.7:
        return "#ff6666"   # red — high confidence
    if confidence >= 0.4:
        return "#ffa366"   # orange — medium confidence
    return "#ffe766"       # yellow — low confidence


# ---------------------------------------------------------------------------
# NavigatorExport
# ---------------------------------------------------------------------------

class NavigatorExport:
    """
    Builds a MITRE ATT&CK Navigator 4.x layer from Sentinel_Fusion alerts.

    Usage:
        layer = NavigatorExport().build(alerts, run_id="abc123")
        # layer is a dict — json.dumps(layer) gives the Navigator JSON
    """

    NAVIGATOR_VERSION = "4.9"
    ATTACK_VERSION    = "14"
    LAYER_VERSION     = "4.5"
    DOMAIN            = "enterprise-attack"

    def build(self, alerts: list[dict], run_id: str = "", description: str = "") -> dict:
        """
        Generate a Navigator layer dict from a list of pipeline alerts.

        Args:
            alerts:      All alerts from PipelineOrchestrator.run()["alerts"].
            run_id:      Pipeline run ID used in the layer name and description.
            description: Optional extra description text.

        Returns:
            Navigator layer dict ready for json.dumps().
        """
        techniques = self._extract_techniques(alerts)

        label = f"Sentinel_Fusion — Run {run_id}" if run_id else "Sentinel_Fusion Detection Layer"
        desc  = description or (
            f"Generated by Sentinel_Fusion on "
            f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}. "
            f"{len(techniques)} technique(s) observed across {len(alerts)} alert(s)."
        )

        return {
            "name": label,
            "versions": {
                "attack":    self.ATTACK_VERSION,
                "navigator": self.NAVIGATOR_VERSION,
                "layer":     self.LAYER_VERSION,
            },
            "domain":      self.DOMAIN,
            "description": desc,
            "filters": {
                "platforms": ["Windows", "Linux", "macOS", "Network"],
            },
            "sorting":     3,
            "layout": {
                "layout":                "side",
                "aggregateFunction":     "max",
                "showID":                True,
                "showName":              True,
                "showAggregateScores":   False,
                "countUnscored":         False,
            },
            "hideDisabled": False,
            "techniques":   techniques,
            "gradient": {
                "colors":   ["#ffe766ff", "#ffa366ff", "#ff6666ff"],
                "minValue": 0,
                "maxValue": 100,
            },
            "legendItems": [
                {"label": "High confidence (≥70%)",   "color": "#ff6666"},
                {"label": "Medium confidence (40–69%)", "color": "#ffa366"},
                {"label": "Low confidence (<40%)",     "color": "#ffe766"},
            ],
            "metadata": [],
            "links":    [],
            "showTacticRowBackground":        False,
            "tacticRowBackground":            "#dddddd",
            "selectTechniquesAcrossTactics":  True,
            "selectSubtechniquesWithParent":  False,
        }

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _extract_techniques(self, alerts: list[dict]) -> list[dict]:
        """
        Deduplicate and score techniques from the alert list.

        A technique may appear in multiple alerts; we keep the entry with the
        highest confidence score. Sub-techniques (T1234.001) are treated as
        independent entries from their parent (T1234).
        """
        # key: (technique_id, tactic_slug) → best alert seen so far
        best: dict[tuple[str, str], dict] = {}

        for alert in alerts:
            technique_id = _parse_technique_id(
                str(alert.get("mitre_technique") or "")
            )
            if not technique_id:
                continue

            tactic_raw  = str(alert.get("mitre_tactic") or "")
            tactic_slug = _parse_tactic_slug(tactic_raw) or ""
            confidence  = float(alert.get("confidence") or 0.0)

            key = (technique_id, tactic_slug)
            existing = best.get(key)
            if existing is None or confidence > float(existing.get("_confidence", 0)):
                best[key] = {**alert, "_confidence": confidence}

        techniques: list[dict] = []
        for (technique_id, tactic_slug), alert in sorted(best.items()):
            confidence = float(alert.get("_confidence", 0.0))
            score      = round(confidence * 100)
            color      = _confidence_to_color(confidence)

            alert_type  = str(alert.get("alert_type") or "")
            mitre_tech  = str(alert.get("mitre_technique") or technique_id)
            comment     = f"{alert_type} — {mitre_tech}" if alert_type else mitre_tech

            entry: dict = {
                "techniqueID":        technique_id,
                "score":              score,
                "color":              color,
                "comment":            comment,
                "enabled":            True,
                "metadata":           [],
                "links":              [],
                "showSubtechniques":  False,
            }
            if tactic_slug:
                entry["tactic"] = tactic_slug

            techniques.append(entry)

        return techniques
